In [12]:
a = [1,2,3,4,5]

print a
print a[0]
print type(a)

[1, 2, 3, 4, 5]
1
<type 'list'>


In [11]:
import numpy as np

np_a = np.array([1,2,3,4,5])

print np_a
print np_a[0]
print type(np_a)

[1 2 3 4 5]
1
<type 'numpy.ndarray'>


In [14]:
a = np.array([1,2,3,4,5])
print np.size(a)

5


In [17]:
# arange function. Same as python range()
a = np.arange(10)
print a

[0 1 2 3 4 5 6 7 8 9]


In [18]:
print np.arange(10,40,5) #start, end, step
print np.arange(0,2,0.3)

[10 15 20 25 30 35]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [19]:
# linspace array generation. evenly spaced. Different from np.arange()
np.linspace(0,11,10)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [22]:
np.linspace(0,3.14, 50)

array([0.        , 0.06408163, 0.12816327, 0.1922449 , 0.25632653,
       0.32040816, 0.3844898 , 0.44857143, 0.51265306, 0.57673469,
       0.64081633, 0.70489796, 0.76897959, 0.83306122, 0.89714286,
       0.96122449, 1.02530612, 1.08938776, 1.15346939, 1.21755102,
       1.28163265, 1.34571429, 1.40979592, 1.47387755, 1.53795918,
       1.60204082, 1.66612245, 1.73020408, 1.79428571, 1.85836735,
       1.92244898, 1.98653061, 2.05061224, 2.11469388, 2.17877551,
       2.24285714, 2.30693878, 2.37102041, 2.43510204, 2.49918367,
       2.56326531, 2.62734694, 2.69142857, 2.7555102 , 2.81959184,
       2.88367347, 2.9477551 , 3.01183673, 3.07591837, 3.14      ])

In [25]:
# reshape matrix (1x12 <-> 2x6 <-> 3x4 etc..)
a = np.arange(15)
b = a.reshape(3,5) # 3 rows, 5 columns
print a
print b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [30]:
a = np.arange(10)
print a
print a+10
print a*10

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[ 0 10 20 30 40 50 60 70 80 90]


In [33]:
# zeros. N-dimensional arrays of zeros. Floating points
print np.zeros(5)

[0. 0. 0. 0. 0.]


In [34]:
print np.zeros((3,4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
print np.ones((4,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
a = np.arange(10)
b = np.sin(a)
print a
print b


[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [39]:
print a**3
print np.max(b)
print np.mean(b)
print np.sum(b)

[  0   1   8  27  64 125 216 343 512 729]
0.9893582466233818
0.195520948210738
1.9552094821073802


In [40]:
# it also works
print b.max()
print b.mean()
print b.sum()

0.9893582466233818
0.195520948210738
1.9552094821073802


In [41]:
# Index of max
b.argmax()

8

In [45]:
c = np.arange(15).reshape(3,5)
print c

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [49]:
print np.sum(c, axis = 0) #sum of each column
print np.sum(c, axis = 1) #sum of each row

[15 18 21 24 27]
[10 35 60]


In [48]:
print np.max(c, axis = 0)
print np.max(c, axis = 1)

[10 11 12 13 14]
[ 4  9 14]


In [52]:
#selecting numbers
a = np.arange(10)**3
print a
print a[2]
print a[2:5]

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]


In [54]:
print a[2:8:2] #array[start, end, step]
print a
print a[::-1] # -1 -> last element

[  8  64 216]
[  0   1   8  27  64 125 216 343 512 729]
[729 512 343 216 125  64  27   8   1   0]


In [56]:
#selecting numbers - Another Example
# create a 10 x 10 array
mat = np.arange(0,100).reshape(10,10)
print mat

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [57]:
# selecting certain number
mat[4,3]

43

In [58]:
# Slicing. Important for Image Processing!!
mat[:,0:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51],
       [60, 61],
       [70, 71],
       [80, 81],
       [90, 91]])

In [59]:
mat[1:3,0:2]

array([[10, 11],
       [20, 21]])

In [60]:
mat[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [65]:
# Returns a matrix of booleans. Thus,
mat_filter = (mat % 3 == 0)
print mat_filter

[[ True False False  True False False  True False False  True]
 [False False  True False False  True False False  True False]
 [False  True False False  True False False  True False False]
 [ True False False  True False False  True False False  True]
 [False False  True False False  True False False  True False]
 [False  True False False  True False False  True False False]
 [ True False False  True False False  True False False  True]
 [False False  True False False  True False False  True False]
 [False  True False False  True False False  True False False]
 [ True False False  True False False  True False False  True]]


In [66]:
print mat[mat_filter]

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [67]:
a = np.arange(10)
print a
print np.where(a>5)
print np.where(a%2==1)
print a%2
print a%2==0

[0 1 2 3 4 5 6 7 8 9]
(array([6, 7, 8, 9]),)
(array([1, 3, 5, 7, 9]),)
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]


In [68]:
#polynomial operation
a = np.arange(15)
coefficients = [1,2,3]
f = np.poly1d(coefficients) #f = 1*x^3 + 2*x^2 + 3
result = np.zeros((np.size(a),2))
result[0:,0] = a
result[0:,1] = f(a)

print result

[[  0.   3.]
 [  1.   6.]
 [  2.  11.]
 [  3.  18.]
 [  4.  27.]
 [  5.  38.]
 [  6.  51.]
 [  7.  66.]
 [  8.  83.]
 [  9. 102.]
 [ 10. 123.]
 [ 11. 146.]
 [ 12. 171.]
 [ 13. 198.]
 [ 14. 227.]]


In [73]:
# Random values
print np.random.randint(0, 10)
print np.random.randint(0, 10)
print np.random.randint(0, 10)

0
2
9


In [75]:
# Random 2D Array
np.random.randint(0,100, (3,3))

array([[45, 41, 38],
       [ 2, 61, 77],
       [96, 26, 20]])